[tox]
envlist = py38, py314
isolated_build = true
skip_missing_interpreters = true

[testenv]
description = Run test suite with pytest
deps =
    pytest
setenv =
    PYTHONPATH = {toxinidir}/src
commands =
    pytest -q

